
# Find one person
GET http://localhost:3001/people/1
###

# Delete a person and all survey logs
DELETE http://localhost:3001/people/4
###

# Add a new survey
POST http://localhost:3001/people/survey
content-type: application/json

{
    "fullName": "John Smith",
    "birthday": "1971-09-12T00:00:00.000",
    "happyScale": 4,
    "energyScale": 3,
    "hopefulnessScale": 2,
    "sleepHours": 8
}
###

# Compare a person to others of same age
GET http://localhost:3001/people/2/compare/age

###

# Compare a person to others using many age groups
# Age groups: 0-10, 11-15, 16-21, 22-30, 31-40, 41-50, 51-70, 71-infinity
# Missing group 51-54 ???
GET http://localhost:3001/people/2/compare/age-groups